pool:
  name: Calculator-Exercise-AGP
  demands:
  - agent.name -equals M0027-NEW
  
steps: 




- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @angular/cli'
 
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install'
 

  
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
 
- task: CopyFiles@2
  inputs:
    Contents: 'dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'